mmm

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -41,10 +41,42 @@ jobs:
       - run:
           name: Trigger Sevalla deployment
           command: |
-            curl -X POST \
-               -H "Content-Type: application/json" \
+            RESPONSE=$(curl -s -X POST \
+              -H "Authorization: Bearer $SEVALLA_API_TOKEN" \
+              -H "Content-Type: application/json" \
               "$SEVALLA_DEPLOY_HOOK_URL" \
-              -d '{"docker_image":"'$DOCKER_HUB_USERNAME'/image-resizer-backend:latest"}'
+              -d '{"docker_image":"'$DOCKER_HUB_USERNAME'/image-resizer-backend:latest"}')
+
+            DEPLOYMENT_ID=$(echo "$RESPONSE" | jq -r '.deployment.id')
+
+            echo "Triggered deployment ID: $DEPLOYMENT_ID"
+
+      - run:
+          name: install jq tool
+          command: sudo apt-get update && sudo apt-get install -y jq
+
+      - run:
+          name: Verify deployment
+          command: |
+        
+            while true; do
+              STATUS=$(curl -s -H "Authorization: Bearer $SEVALLA_API_TOKEN" \
+                  "https://api.sevalla.com/v2/applications/$SEVELLA_APP_ID	/deployments/$DEPLOYMENT_ID" \
+                  | jq -r '.status')
+
+              echo "Current deployment status: $STATUS"
+
+              if [[ "$STATUS" == "success" ]]; then
+                echo "Deployment succeeded!"
+                break
+              elif [[ "$STATUS" == "failed" ]]; then
+                echo "Deployment failed!"
+                exit 1
+              else
+                echo "Waiting 10 seconds..."
+                sleep 10
+              fi
+            done
 
     
 workflows:
